### PR TITLE
Add a Dockerfile for building/running noflo-ui in a container

### PR DESCRIPTION
**Pull request by bodom0015**
Using the official Docker image for node boron (LTS), I cooked up a simple Dockerfile for noflo-ui by following the installation instructions in the main repo.

Final image size: ~350MB

A few notes:
* Overriding environment variables at runtime would likely require performing the `grunt build` during container startup, but I'm still trying to find a better pattern for that
* Using **node:boron-alpine** as base image reduced the final image size by ~65% (NOTE: Alpine uses *musl libc* instead of *glibc*, and can be reverted if it causes a problem)

### CODE REVIEW

**Comment by bergie** [comment]
@bodom0015 sorry, didn't get to this today. Will return to the subject on Monday. Thanks again on the PR!

**Comment by bergie** [comment]
Thanks for the contribution! Now we need to consider if we should build this on Travis and push to Docker Hub

**Comment by bodom0015** [comment]
Awesome news! :D

I am not as familiar with Travis as I should be but if integrating with it directly turns out to be difficult, DockerHub can perform automated builds on a GitHub repo separate from the Travis build. It's not ideal (DockerHub builds very slowly) or extensible, but it has a low barrier to entry and works fairly well.

**Comment by bergie** [comment]
@bodom0015 the benefit of using Travis would be that then it'd be part of our standard CI and release pipeline.

I've done similar things with other web apps, for example: https://github.com/c-base/cbeam-telemetry-server

**Comment by bodom0015** [comment]
Ah, perfect! If you've already got a pattern for doing these things, then I won't get in your way hehe

Thank you, @bergie! :)

**Comment by bergie** [comment]
We have automated Docker builds configured now:

https://hub.docker.com/r/flowhub/noflo-ui/

**Pull request merged**
