### PR TITLE
Bundle Polymer elements from the-graph

### PR DESCRIPTION
**Pull request by jonnor**
Refs #537 

Seems to work just fine. 
Only the import paths was changed wrt to the original code.

These elements will be removed from the-graph as soon as there is a way to use the functionality without Polymer. Nav and thumb are already gone in git master.

Might want to wait until https://github.com/flowhub/the-graph/pull/356 is completed. It may be that existing PolymerGestures will have issues when going to Polymer 1.0+

### CODE REVIEW

**Comment by bergie** [comment]
Thanks! With this we should be able to proceed with #668

**Comment by bergie** [comment]
@jonnor do you feel this is good to integrate already?

**Comment by jonnor** [comment]
From noflo-ui POV maybe. It doesn't seem to break anything, and there is no change.
Of course the APIs used might be broken in the-graph, but that's a constant since that project doesn't have any tests or even a well defined API.

**Comment by bergie** [comment]
OK, I think then we just merge. And as soon as the-graph doesn't depend on Polymer any longer we proceed with the 1.x port.

**Pull request merged**
