### PR TITLE
Load examples for available runtimes from runtime info files

### LINKED ISSUE #617: Configure examples to show on build time
Unless I overlook something, there is no way to configure the examples to appear on the noflo-ui home page. They seem to be hardcoded in `noflo-main.html`, with no way to override them. It would be useful to configure them when noflo-ui is built, so that examples can be customized, e.g. for new runtimes or for personal examples.

What would be the best solution for you? There is an `examples.json` file in the project root which doesn't seem to be used anywhere... It would be nice to include it in `noflo-main.html` someway. The easiest way I can think of is to define a `$NOFLO_EXAMPLES_JSON` variable in the Gruntfile loading `examples.json` and using it in `noflo-main.html`, but it seems a bit hackish. What do you think?

### PR DESCRIPTION
**Pull request by ruippeixotog**
Fixes #617 by adding information about the examples for each runtime type in the runtime info YAML files. As runtimes are updated in the UI, so are the examples.

### CODE REVIEW

**Comment by ruippeixotog** [comment]
I'm not used to work with Polymer and I'm still learning how the code is organized in noflo-ui, so I may have implemented the feature in the wrong place or done something not idiomatic for the framework. If that's the case, tell me and I'll be happy to change it.

**Comment by ruippeixotog** [comment]
@jonnor, have you had a chance to read this pull request?

**Comment by jonnor** [comment]
@ruippeixotog I forgot, thanks for the ping!

I pulled and built the app. However, when I now open it, the "Examples" section on frontpage has no examples listed. So I suspect that something is a little bit wrong with the logic in `noflo-main.html`?

**Comment by ruippeixotog** [comment]
Damn, I never tested the UI when logged out... Sorry, should be fixed now!

**Comment by jonnor** [comment]
Merged. Thanks!

**Pull request merged**
