### PR TITLE
Fix multiple node selection

### LINKED ISSUE #1032: Group creation / selection doesn't seem to work
I can see it is possible to create groups because they appear to be there in the ReactTodoExample.  However, it isn't clear at all how multi-select is supposed to work.  Does multiple selection actually work on Windows, or is this related to: https://github.com/noflo/noflo-ui/issues/28?

### PR DESCRIPTION
**Pull request by bergie**
Fixes #1032

### CODE REVIEW

**Comment by WilliamRClark** [comment]
@bergie  Excellent.  I started looking at the-graph dependency, and realized it actually doesn't build because of the version of canvas.js that they are using.  I'm submitting a PR to them, but I don't know if they want a dependency added to noflo-canvas instead of noflo-prebuilt which has dropped the build they rely on.

**Comment by WilliamRClark** [comment]
@bergie This is the issue with the-graph dependency.  https://github.com/flowhub/the-graph/issues/392

**Comment by bergie** [comment]
@WilliamRClark PR to fix the-graph build would be very welcome 😄

**Comment by bergie** [comment]
What's remaining with this PR is to change timing of when the subgraph changes are made: we need the new subgraph to be fully registered with the runtime before we send the node changes to the main graph. 

With NoFlo this became necessary with noflo/noflo#611

**Comment by WilliamRClark** [comment]
> @WilliamRClark PR to fix the-graph build would be very welcome 😄

Best attempt.
https://github.com/flowhub/the-graph/pull/393

**Pull request merged**
